Access to Sound#valueOf method through Reflection to avoid java.lang IncompatibleClassChangeError when using versions prior to 1.21.3
HelpChat/DeluxeMenus pull request #158
Opened 2024-12-01 09:16 UTC by MemencioPerez

Seems to fix #157

2024-12-01 11:42 UTC, Tanguygab commented
I think it'd just be better if we finally switched to the method with a String parameter for the sound, that way custom sounds can finally be used. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#playSound(org.bukkit.Location,java.lang.String,float,float)

2025-01-12 00:50 UTC, BlitzOffline requested changes

2025-01-12 00:50 UTC, BlitzOffline commented on src/main/java/com/extendedclip/deluxemenus/utils/SoundUtils.java
> +        } catch (Exception e) {
If we know an IncompatibleClassChangeError will be thrown, we should catch it instead of a general catch.

Catching like this might hide future issues.

2025-01-12 07:57 UTC, MemencioPerez commented on src/main/java/com/extendedclip/deluxemenus/utils/SoundUtils.java
> +        } catch (Exception e) {
An IncompatibleClassChangeException will not be thrown since the valueOf method is being called using Reflection, possible exceptions are ClassNotFoundException, NoSuchMethodException, IllegalAccessException, and InvocationTargetException.

2025-01-14 00:29 UTC, BlitzOffline approved these changes

2025-01-14 00:38 UTC, Kqliber approved these changes

2025-01-14 00:38 UTC, merged