feat: add nexo support
HelpChat/DeluxeMenus pull request #161
Opened 2024-12-08 20:14 UTC by simondumalski

I have created this pull request that adds Nexo support to DeluxeMenus. I have tested this on my development server and have not encountered any issues. The implementation is nearly identical to the existing Oraxen hook.
Some things to note:
- The Nexo API requires Java 21, so I have had to update the target and source compatibility to that.
- The existing shadow plugin is not compatible with Java 21, so I have updated it to the shadow plugin that is being maintained by Gradle.

2024-12-09 19:01 UTC, iGabyTM requested changes
We can't just bump the java version by 10 releases to add support for a plugin. This needs to be announced first.

2024-12-09 19:12 UTC, simondumalski commented
> We can't just bump the java version by 10 releases to add support for a plugin. This needs to be announced first.

Yes, this PR is more to let HelpChat know that if they want to support Nexo, they'll have to update to Java 21, as well as add the hook itself so that if anyone wants to compile it themselves, they can. Other plugins that have added Nexo support have marked their Oraxen support as Deprecated, such as CrazyCrates and HMCCosmetics.

2024-12-17 06:03 UTC, FaultyFunctions commented
Any news on this?

2024-12-19 14:59 UTC, simondumalski commented
I've been told a version of the Nexo API that doesn't require Java 21 is potentially being worked on. Will update this if that ever comes out.

2025-01-11 22:54 UTC, NoltoxGit commented
Hi!
I've just looked, and there are more than 60% of servers using **DeluxeMenus** running **Java 21** (or higher like 22, 23...).

So yeah, I can understand this change requires an announcement, but it only affects a minority of servers, especially since the servers using a version lower than **Java 21**, they are also using an old version of DeluxeMenus ^-^

> https://bstats.org/plugin/bukkit/DeluxeMenus/445#javaVersion

![image](https://github.com/user-attachments/assets/ea0fef78-3617-4cdf-ad0f-1f5ca70ed05f)

2025-01-17 02:06 UTC, qckcat commented
Also looking for Nexo support in DeluxeMenus - Don't most modern server wrappers prefer Java 21 at this point?

2025-02-04 10:52 UTC, LichtHund commented
The change of the version would "only" affect a minority, but that is still a whopping 40% of users. In this case you _can_ use `disableAutoTargetJvm()` to allow importing of Nexo API while still keeping the target at JVM 11; since it is only required by a single class anyways.

2025-04-06 19:35 UTC, BlitzOffline commented
Closing this in favor of #181

2025-04-06 19:35 UTC, closed without merging