Add Executable Items / Block Support
HelpChat/DeluxeMenus pull request #52
Opened 2024-01-08 16:29 UTC by Oribuin

Implement ExecutableItems and ExcecutableBlocks support for deluxemenus.

ExecutableBlocks seems to have a lack of information regarding their maven dependency with the one provide being outdated and missing from repositories, Suppressing deprecation is not ideal.

2024-01-08 18:06 UTC, iGabyTM commented on src/main/java/com/extendedclip/deluxemenus/utils/Constants.java
> +    public static final String EXECUTABLEITEMS_PREFIX = "ei-";
Please use the full name for the prefix, same for the other.

2024-01-08 18:07 UTC, iGabyTM requested changes

2024-01-08 18:07 UTC, iGabyTM commented on src/main/java/com/extendedclip/deluxemenus/utils/Constants.java
> +    public static final String EXECUTABLEITEMS_PREFIX = "ei-";
Please use the full name for the prefix, `executableitems-` and `executableblocks-`.

2024-01-08 18:10 UTC, BlitzOffline requested changes

2024-01-08 18:10 UTC, BlitzOffline commented on src/main/java/com/extendedclip/deluxemenus/utils/Constants.java
> +    public static final String EXECUTABLEBLOCKS_PREFIX = "eb-";
Could we make these more specific? `executableitems-` and `executableblocks-` is not that bad. If people disagree, we could at least make them `execitems-` and `execblocks-`.

2024-01-08 18:10 UTC, BlitzOffline commented on src/main/java/com/extendedclip/deluxemenus/hooks/ExecutableBlocksHook.java
> +  @SuppressWarnings("deprecation")
This is indeed not that nice. After looking at a decompiled version of the plugin, it seems that it does indeed have an API and the wiki suggests using the JAR directly. No remote repository is provided.

I guess, for now we'll support the deprecated version until the developer decides to completely remove it or they provide an online version of the dependency..

2024-01-08 21:44 UTC, Oribuin commented
I'd like to hold this pull request off until #53 is merged so that both branches can work together.

2024-01-08 21:48 UTC, iGabyTM submitted a review, later dismissed

2024-01-09 23:02 UTC, Kqliber submitted a review, later dismissed

2024-01-10 20:18 UTC, Oribuin commented
FIxed all the merge conflicts with main, everything should be ready to go.

2024-01-11 21:46 UTC, BlitzOffline commented
There seems to still be some merge conflicts. Also, considering Gaby suggested it as well, I think it is best to use `executableitems-` and `executableblocks-`. The only hook still using short names is the HeadDatabase one for backwards compatibility.

2024-01-11 22:21 UTC, Oribuin commented
Fixed merge conflict as it was literally just an extra space.

Changed execitems/execblocks to executableitems/executableblocks

2024-01-12 22:22 UTC, BlitzOffline requested changes

2024-01-12 22:22 UTC, BlitzOffline commented on src/main/java/com/extendedclip/deluxemenus/utils/Constants.java
> +    public static final String EXECUTABLEBLOCKS_PREFIX = "execblocks-";
Are these constants used anywhere anymore? If yes, they should be changed. If no, they should be removed.

2024-01-22 09:45 UTC, BlitzOffline approved these changes

2024-01-22 22:06 UTC, merged